# Generated by Django 5.2.9 on 2026-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
