# Generated by Django 5.2.9 on 2026-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscription_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("CREATED", "создан"), ("PAID", "оплачен")],
                default="CREATED",
                max_length=8,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
