# Generated by Django 5.2.9 on 2026-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата оплаты"),
        ),
    ]
