# Generated by Django 5.2.9 on 2026-01-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_payment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="created_at",
            new_name="created_date",
        ),
    ]
