# Generated by Django 5.2.9 on 2026-01-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_created_at_payment_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(blank=True, max_length=500, null=True, verbose_name="<UNK> <UNK> <UNK>")),
                ("session_id", models.CharField(max_length=100, verbose_name="<UNK> <UNK>")),
                ("price_id", models.CharField(max_length=100, verbose_name="<UNK> <UNK>")),
                ("product_id", models.CharField(max_length=100, verbose_name="<UNK> <UNK>")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.payment", verbose_name="Платеж"
                    ),
                ),
            ],
        ),
    ]
