# Generated by Django 5.2.9 on 2026-01-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="price_id",
            field=models.CharField(max_length=100, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="product_id",
            field=models.CharField(max_length=100, verbose_name="Продукт"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="session_id",
            field=models.CharField(max_length=100, verbose_name="Сессия"),
        ),
    ]
