# Generated by Django 5.2.9 on 2026-01-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_transfer_link_alter_transfer_price_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfer",
            options={"ordering": ["payment"], "verbose_name": "перевод", "verbose_name_plural": "переводы"},
        ),
    ]
