# Generated by Django 5.2.9 on 2026-01-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_transfer_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="owner",
        ),
    ]
