# Generated by Django 5.2.9 on 2026-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_stripe_product_id_lesson_stripe_product_id"),
        ("users", "0013_rename_user_payment_owner"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("paid_course__isnull", False), ("paid_lesson__isnull", True)),
                    models.Q(("paid_course__isnull", True), ("paid_lesson__isnull", False)),
                    _connector="OR",
                ),
                name="only_one_product_type_check",
            ),
        ),
    ]
