# Generated by Django 5.2.9 on 2026-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на материалы"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на материалы"),
        ),
    ]
