# Generated by Django 5.2.9 on 2026-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Значение product_id в Stripe"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Значение product_id в Stripe"),
        ),
    ]
