# Generated by Django 5.2.9 on 2026-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_stripe_product_id_lesson_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Дата обновления"),
        ),
    ]
